version: '2'
services:
  mongo:
    image: mongo:3.0.4
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles --rest
  petapi:
    image: pet-api
    build:
      context: .
      dockerfile : ./Dockerfile
    container_name: 'pet-api-cont'
    environment:
      MONGODB_URI: mongo
      GOOGLE_CLIENT_ID: '860669888336-9e17ofrmgu3bo01lr8gbfm4e3noforie.apps.googleusercontent.com'
      GOOGLE_CLIENT_SECRET: 'MzJaJGDh955urboHNNcXhd3o'
      DOMAIN: "http://petadoption.org:8080"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
volumes:
  mongodata:
    driver: local
